### ISSUE TITLE
How could I get older posts?

### ISSUE THREAD

**Issue by moehanabi** [sergeyklay/gohugo-theme-ed#132]
If I set _index.md in content, only latest posts will be shown in the homepage. I want to know how I can get all of my posts

**Comment by sergeyklay** [comment]
Hi @moehanabi,

Apologies for the delayed response. There is a configuration parameter called `recentPostsSize` that controls the number of recent posts displayed on the page. For the demo site, you can find its location here: [params.yaml](https://github.com/sergeyklay/gohugo-theme-ed/blob/8be32ec0b7743a2016a38e4e8b7d11930fc2dcf0/exampleSite/config/_default/params.yaml#L54).

Essentially, you need to override this value for your blog with something larger — this is the simplest way to increase the number of posts shown. Just copy the example configuration into your `config/_default/params.yaml` file and modify it as needed.

I hope I understood your request correctly. If you have any further questions, feel free to ask.

**Comment by moehanabi** [comment]
Thanks very much for answering my question.
So now ed doesn't support post list paging (for example, 5 posts a page and I can use "next page" to get next 5 posts) and archieve page (a page list all of my posts) right?

**Comment by sergeyklay** [comment]
If the question is about the homepage, then yes, it is. Currently it's set up that way - we show a small intro and then a short list of recent articles: https://github.com/sergeyklay/gohugo-theme-ed/blob/b2b7d1b5e0cc1db068b94bd9c6fe6a9deb1ade9f/layouts/index.html#L4-L8

 I'll try to think how to improve this

**Comment by moehanabi** [comment]
I see. thanks!
