### ISSUE TITLE
adding a fabform.io contact form

### ISSUE THREAD

**Issue by derrygeoff** [sergeyklay/gohugo-theme-ed#2]
Hello

Is there anyway you can add a https://fabform.io contact form to your theme?

Geoff
https://fabform.io

**Comment by sergeyklay** [comment]
Hello!

Ed theme is not strictly tied to any forms backend. You can easily use any backend like [Formspark](https://formspark.io/), [Formspree](https://formspree.io/), [FabForm](https://fabform.io) and so on just by changing the `formAction` parameter in the site configuration file:
https://github.com/sergeyklay/gohugo-theme-ed/blob/8c3b97e3307764821ca9aade0af6d8f5aa0907d7/exampleSite/config.toml#L152-L158

For a more subtle configuration of the contact form itself, you can also replace `layouts/shortcodes/form-contact.html` partial in project wide level.
