### ISSUE TITLE
Replacing the favicon 

### ISSUE THREAD

**Issue by Fallenstedt** [sergeyklay/gohugo-theme-ed#24]
**Is your feature request related to a problem? Please describe.**
I'm not sure how to override the favicon for this theme. I've added my own favicon in `static/favicon.ico` and it was not able to override it during a build

**Describe the solution you'd like**
When a user adds a favicon in static, it overrides the theme's favicon at build time 

**Describe alternatives you've considered**
For now, I'm manually adding the favicon to my built directory on each build

**Comment by sergeyklay** [comment]
Hm, I use `static/favicon.ico` to override it. Take a look: https://github.com/sergeyklay/blog/tree/master/static

**Comment by Fallenstedt** [comment]
🤦 Wow. I I had this in `static/images/favicon.ico`. Thank you for helping me see my mistake.

**Comment by sergeyklay** [comment]
You're welcome
