### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by hhemied** [sergeyklay/gohugo-theme-ed#29]
Adding Dark mode will be very valuable for a theme like Ed.
It is almost perfect for researchers, but missing Dark mode.

**Comment by sergeyklay** [comment]
Hi, I have almost no experience in creating dark themes. Also, I'm not having any free time these days. For all that, if someone would provide a patch, I'd be happy to.

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
