### ISSUE TITLE
Theme and Font Styling

### ISSUE THREAD

**Issue by pavel-hrdina** [sergeyklay/gohugo-theme-ed#40]
**Is your feature request related to a problem? Please describe.**
I am trying to change the color theme and fonts of the website, but despite multiple attempts, I have been unsuccessful in achieving the desired changes.

**A clear and concise description of what the problem is.**
I have made changes to the resources in the **resources/assets** folder of my project, including modifying values and creating a `style.scss` file. However, these changes are not being applied when I run the project. The project continues to display the old styles and values, ignoring the modifications I made.

**Describe the solution you'd like**
I would like to be able to successfully change the color theme and fonts of the website. Specifically, I expect the modifications I make in the **resources/assets** folder, such as adjusting values and creating a `style.scss` file, to be accurately reflected in the color scheme and fonts displayed on the website.

**Describe alternatives you've considered**
I have considered various alternatives to address this problem, including:

1. Verifying that the changes made in the **resources/assets** folder are saved properly and are being overwritten during the build or deployment process.

2. Checking for any conflicting styles or settings that may be overriding the color theme and font changes.

3. Exploring the configuration files to ensure that the updated color theme and font assets are being included and applied correctly.

**Additional context**
Here are some additional details and information that may be helpful in understanding the issue:

1. The website successfully builds and runs without any apparent errors.

2. I have reviewed the console and logs for any relevant error messages, but there are no error messages related to the color theme or fonts.

3. If necessary, I can provide screenshots of the **resources/assets** folder structure or any other relevant files to assist in troubleshooting the issue

**Comment by andergisomon** [comment]
Have you found a fix?

**Comment by sergeyklay** [comment]
To change the main color accents of the theme, such as the headers, links, and text logo, you can use the `colorScheme` configuration parameter, as shown below:

~~~ yaml
params:
  colorScheme: magenta
~~~

The demo site uses a feature that splits configuration into separate files, so if your project follows the same structure, the `colorScheme` parameter should be located in the `params.yaml` file, simply at the root, like this:

~~~ yaml
colorScheme: blue
~~~

The currently supported colors are: red, orange, magenta, cyan, blue, and brown.

If no value is provided, or if you remove the `colorScheme` parameter altogether, the theme defaults to red.

At the moment, the theme does not support arbitrary changes to fonts, custom colors, or other visual elements beyond those predefined by the theme. However, the theme provides a way for you to add your own custom styles to your project.

To do this, create a `layouts/partials` directory in your project, and inside it, add a file named `custom-head.html`. You can now define any custom styles within this file. For example:

~~~ html
<style>
    html {
        font-family: "PT Sans", Helvetica, Arial, sans-serif;
    }
</style>
~~~

This allows you to override or extend the theme’s default styles with your own customizations.

Let me know if you have any questions or need further clarification!

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
